version: "3.8"

services:
  postgres:
    #  Имя контейнера.
    container_name: postgres
    #  Образ контейнера.
    image: postgres:13
    # Перезапускать контейнер всегда, кроме случаев, когда он остановлен явно.
    restart: unless-stopped
    environment:
      # Имя базы данных.
      POSTGRES_DB: ai_creative_platform
      # Имя пользователя.
      POSTGRES_USER: ${POSTGRES_USER:-ai_creative_platform_user}
      # Пароль пользователя.
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-5555}
    ports:
      # Открываем порт 5432 на хост-машине.
      - '5432:5432'
    volumes:
      # Монтируем папку с данными в контейнер.
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local